### ISSUE TITLE
1. c.  Reproduce the matlab results : curvature

### ISSUE THREAD

**Issue by alexpron** [brain-slam/slam#102]
In the matlab code, the Gauss-Bonnet scheme to estimate the curvature is used. It is a simplification of the formula found on page 3 for H
http://kowon.dongseo.ac.kr/~lbg/web_lecture/grapprog/20122/cag2002.pdf

In the spangy paper of 2012 we used the method by Desbrun, _Implicit fairing of irregular meshes using diffusion and curvature ﬂow_, 1999

**Comment by GerardMJuan** [comment]
The curvature results are not identical with the SLAM implemented method () and the SPANGY implemented method in matlab. When calculating the differences across  the two curvatures, we find small differences:

![Image](https://user-images.githubusercontent.com/3297549/204491861-bdc73b59-6ad9-4268-946b-1e3955cdd2bc.png)
![Image](https://user-images.githubusercontent.com/3297549/204491901-c5a33780-2d0c-48d5-882c-bf392416e647.png)

Histogram of differences:

![Image](https://user-images.githubusercontent.com/3297549/204492386-1b4f79ee-07f8-4436-87a3-128410c263a8.png)

Mean diff 0.1895964980154496
Median diff 0.15392203522372663
Max 3.9165127822562016
Min 0.0004220763468907587

It also affects the spectrum results (see next issue)
