### ISSUE TITLE
1. d. reproduce the matlab results : spectrum

### ISSUE THREAD

**Issue by alexpron** [brain-slam/slam#103]

**Comment by GerardMJuan** [comment]
We adapted the already implemented spangy_spectrum() function in python to compute the spectrum and generate the same figure than in the MATLAB code. Given the differences in curvature obtained with the two different methods, we tried to generate the spectrum with each platform and each curvature, so 4 results in total.

**For the SLAM generated curvature:**

**Python results:**

![Image](https://user-images.githubusercontent.com/3297549/204496033-3d624dc9-8f93-48f2-9f38-328ac72a8f5a.png)

Spectral bands values:
[[14.16534226]
 [ 3.63925997]
 [ 8.69843902]
 [10.92130688]
 [18.3210126 ]
 [ 6.4831803 ]
 [ 1.42961411]]

**MATLAB results:**

![Image](https://user-images.githubusercontent.com/3297549/204496057-9c5b4918-8359-4ca2-8401-3edd3ef6dba1.png)

14.1653422633940
3.63925996931672
8.69843902396158
10.9213068752227
18.3210125984343
6.48318029617731
1.42974116586035

**For the MATLAB generated curvature:**

**Python results:**

![Image](https://user-images.githubusercontent.com/3297549/204496090-e6702196-5544-40c6-a159-afb4e22ba423.png)

[[19.5671609 ]
 [ 3.51731383]
 [ 7.27312917]
 [ 9.11772963]
 [17.16747587]
 [ 6.59756399]
 [ 1.23139443]]

**MATLAB results:**

![Image](https://user-images.githubusercontent.com/3297549/204496101-0a2820d4-1c28-4f2b-a83b-a4898aa0983c.png)

19.5671609028560
3.51731382744039
7.27312917408920
9.11772963090126
17.1674758717667
6.59756399360253
1.23209039676390 

So, differences depending on the curvature, but results are identical across platforms with the same curvature, with still some small issues in the plot of the frequency that can be ironed out.

**Comment by GerardMJuan** [comment]
Plotting has been updated to be equal to the MATLAB code. The coefficients obtained are identical across codes (when using the same curvature), but sometimes they have the sign flipped.

Should the plot function be added to the slam plot library? Or is too much of a general plot?

**Comment by JulienLefevreMars** [comment]
Slam has no dependency to matplotlib but we can add another requirement specific to the spangy module. Thank you @alexpron for the indication.
