### ISSUE TITLE
Dependencies: shapely

### ISSUE THREAD

**Issue by gauzias** [brain-slam/slam#63]
We should have a look at shapely and how it is used in trimesh.
We can then decide either 
1- to avoid this dependency by not using corresponding functionalities in from trimesh, or
2- to integrate and use shapely much more, especially in the topology module

**Comment by JulienLefevreMars** [comment]
I rapidly went through the doc
https://shapely.readthedocs.io/en/latest/
I am not sure that shapely is of great use for topologic or geometric aspects

I have not found an easy way to retrieve which modules of trimesh use shapely but I observed that it is used in trimesh.creation that is used in slam to generate an icosphere.

Is there a specific problem with shapely ? I am not sure but I might have had some troubles with it in the past, in slam.

**Comment by alexpron** [comment]
Thank you very beaucoup @JulienLefevreMars  for investigating this dependency problem. Shapely was removed from the dependencies for installation purpose. Hence I close this issue. Dont 'hesitate to reopen it if use case with shapely appears
