### ISSUE TITLE
Adding a rotation parameter in the visbrain_plot function

### ISSUE THREAD

**Issue by JulienLefevreMars** [brain-slam/slam#67]
Hello,

It could be good to add a simple feature to offer views of meshes with different view points (typically azimuth and elevation). 
Several strategies:

- One way could consist in applying a transformation to the mesh in the `visbrain_plot` function. It may be a problem that the mesh remains rotated after the visualization. A possibility to compensate the rotation once the figure is closed ?
- Another way could be to rotate the camera of the scene but it seems to be less obvious to retrive the good attributes in the Scene Obj

**Comment by alexpron** [comment]
Ty @JulienLefevreMars for Issue. It would be a nice feature indeed. To be dig further after the slam and vector field meeting depending on what will be decided :)
