### ISSUE TITLE
[DOC] doc string determine_local_basis is missing

### ISSUE THREAD

**Issue by MaximeDdnn** [brain-slam/slam#81]
hello,
I would like to use the determine_local_basis function in curvature.py. but i'm confused about the inputs and the outputs format.
For example how should I reshape  my input "normal" . How to define the proj_matrix and which tolerance should i use ?

I understand that this function is used in the function fit_curvature but i dont understand how to initiate my imputs arguments

thanks for your help,

**Comment by JulienLefevreMars** [comment]
Hello @MaximeDdnn ,

The function is confusing indeed: I propose to add some comments to clarify. Briefly:
- the normal vector should be 3 x1
- the proj_matrix is obtained through the curvature_fit function. There is no tolerance but the if in determine_local_basis_function is there to avoid a projection to a null vector if the normal equal [[1],[0],[0]]
